/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 html.gltf --transform
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html-logo-3d-model-ab8b32cab3364027ab00a033a0b2ff38
Title: HTML logo 3d model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/landingPage/html-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group
          position={[0, 7.94, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.009}
        >
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.009"]}
          position={[18.96, 117.48, 10.53]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.009}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Material.012"]}
          position={[42.71, 209.04, 23.56]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/landingPage/html-transformed.glb");
