/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logos2.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/landingPage/logos2-transformed.glb");

  // const iconsRef = useRef(null);

  // useFrame(
  //   (state) =>
  //     (iconsRef.current.rotation.z =
  //       Math.abs(Math.sin(state.clock.getElapsedTime() * 0.09) * 100) * 0.05)
  // );

  return (
    <group
      // ref={iconsRef}
      {...props}
      dispose={null}
      rotation={[-10, -7.9, -10]}
      position={[-4.6, -1.07, -2.84]}
    >
      <group position={[-2.6, 2.07, -4.84]} scale={[0.71, 0.65, 1.1]}>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Cube008_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Cube008_2.geometry}
          material={materials["Material.020"]}
        />
      </group>
      <group
        position={[-2.59, 1.82, -6.03]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.35}
      >
        <mesh
          geometry={nodes.Text003.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Text003_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Text003_2.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Text003_3.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Text003_4.geometry}
          material={materials["Material.019"]}
        />
      </group>
      <group
        position={[-2.51, 2.16, -9.41]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.26}
      >
        <mesh
          geometry={nodes.Text004.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Text004_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Text004_2.geometry}
          material={materials["Material.019"]}
        />
      </group>
      <group
        position={[-2.57, -0.19, -1.29]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.31}
      >
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Text_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Text_2.geometry}
          material={materials["Material.019"]}
        />
      </group>
      <group position={[-2.49, 0.41, -8.7]} scale={[0.78, 0.78, 1.97]}>
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Cube011_2.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group
        position={[-2.72, 2.03, -1.98]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.31}
      >
        <mesh
          geometry={nodes.Text006.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Text006_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Text006_2.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          geometry={nodes.Text006_3.geometry}
          material={materials["Material.027"]}
        />
      </group>
      <group position={[-2.67, 0.4, -6.17]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.68, 0.43, -3.91]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/logos2-transformed.glb");
