/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 react.gltf --transform
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-circle-540ff21ac0f54a038df6f634c7cce726
Title: React logo circle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/landingPage/react-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes["React-Logo_Material002_0"].geometry}
            material={materials["Material.002"]}
            position={[0, 7.94, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[10.17, 10.17, 13.73]}
          />
          <mesh
            geometry={nodes.Backdrop_Material001_0.geometry}
            material={materials["Material.001"]}
            position={[-17.09, 7.94, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[78.85, 78.85, 13.73]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/landingPage/react-transformed.glb");
