/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 spaceship-2.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/landingPage/spaceship-2-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -376.02, 0]}>
          <group position={[4.67, 278.7, 0]} rotation={[0, -0.71, 0]}>
            <mesh
              geometry={nodes.mesh_6_instance_0.geometry}
              material={materials["default"]}
              position={[35, 0, 0]}
            />
            <mesh
              geometry={nodes.mesh_6_instance_1.geometry}
              material={materials["default"]}
              position={[0, 0, 35]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes.mesh_6_instance_2.geometry}
              material={materials["default"]}
              position={[-35, 0, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.mesh_6_instance_3.geometry}
              material={materials["default"]}
              position={[0, 0, -35]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <pointLight
            intensity={1}
            decay={2}
            distance={5387}
            color="#ffb189"
            position={[0, 59.62, -225.24]}
          />
          <pointLight
            intensity={1}
            decay={2}
            distance={5387}
            color="#ffb189"
            position={[0, 59.62, 113.79]}
          />
          <mesh
            geometry={nodes.Blur_effect.geometry}
            material={materials["default"]}
            position={[1.75, -189.66, 1.01]}
            scale={[3, 7, 3]}
          />
          <mesh
            geometry={nodes.Fire.geometry}
            material={materials["default"]}
            position={[1.11, -133.13, 1.01]}
            scale={[2, 5.39, 1.97]}
          />
          <mesh
            geometry={nodes.Cap.geometry}
            material={materials["default"]}
            position={[1.18, 465.26, 34.17]}
            scale={[0.86, 1, 1]}
          />
          <mesh
            geometry={nodes.Bottom2.geometry}
            material={materials["default"]}
            position={[-0.37, 125.37, 1.08]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={materials["default"]}
            position={[-0.37, 141.64, 1.08]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.BODY.geometry}
            material={materials["default"]}
            position={[0, 376.02, 0]}
            rotation={[-Math.PI, -0.09, -Math.PI]}
            scale={5}
          />
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[121.98, -238.14, 1028.73]}
          rotation={[0.13, 0.1, -0.01]}
        />
        <directionalLight
          intensity={1}
          decay={2}
          rotation={[-1.21, 0.22, 1.49]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[98.36, 49.07, 1048.1]}
          rotation={[-0.07, 0.09, 0.01]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/spaceship-2-transformed.glb");
