// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import { useGLTF } from "@react-three/drei";
// import React, { useRef } from "react";
// import { fadeOnBeforeCompile } from "@/utils/fadeMaterial";
// import { useFrame } from "@react-three/fiber";

// export function Cloud({ sceneOpacity, opacity, ...props }) {
//   const { nodes, materials } = useGLTF("/experience/model.gltf");

//   const materialRef = useRef();

//   useFrame(() => {
//     materialRef.current.opacity = sceneOpacity.current;
//   });

//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Mball001.geometry}>
//         <meshStandardMaterial
//           ref={materialRef}
//           onBeforeCompile={fadeOnBeforeCompile}
//           envMapIntensity={2}
//           transparent
//         />
//       </mesh>
//     </group>
//   );
// }

// useGLTF.preload("./experience/model.gltf");
