/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 meteor.gltf --transform
Author: d880 (https://sketchfab.com/distance880)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/stoney-asteroids-9c03507d9f5b4e509bc90791ffbc5ac7
Title: Stoney Asteroids
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Meteor({ sceneOpacity, opacity, ...props }) {
  const { nodes, materials } = useGLTF("/experience/meteor-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Material_001}
        ></mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/experience/meteor-transformed.glb");
