/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 meteor.gltf --transform
Author: laboratorija (https://sketchfab.com/laboratorija)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/meteorite-f649328ea80c426eb500477c6d6e4734
Title: Meteorite
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/experience/meteor-transformed.glb");
  return (
    <group {...props} dispose={null} scale={[.5, 0.5, 0.5]}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material__25}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/experience/meteor-transformed.glb");
