/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 guard.gltf --transform
Author: adamnsexyname (Pieter) (https://sketchfab.com/adamnsexyname)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guard-9d21df6ad131402cafb2fb5851683158
Title: guard
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/payment/guard-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -3, -3]}>
        <mesh
          geometry={nodes.Plane_0.geometry}
          material={materials.Plane_0}
          position={[-7.34, 0.52, 5.11]}
          rotation={[0.72, -1.1, -1.93]}
          scale={0.1}
        />
        <mesh
          geometry={nodes.Cylinder000_0.geometry}
          material={materials.wapen}
          position={[-1.56, -0.12, 3.06]}
        />
        <mesh
          geometry={nodes.Avatar001_0.geometry}
          material={materials.personage}
          position={[0.03, 0.74, 2.94]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/payment/guard-transformed.glb");
